name: Bounty Scope Checker

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  check-scope:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scope check
        run: |
          python Whaching.py

      - name: Commit & push if changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add *.json
          git commit -m "🔄 Update scope data" || echo "No changes"
          git push
